### ISSUE TITLE
NOT ISSUE

### ISSUE THREAD

**Issue by esraamohammedelghorab** [CSEA-AUC/CSEA-Summer24-Internships#4]
Hi ALL, I Want to thank you all for your Efforts.
IF you can to provide some Embedded Systems and IOT internships or researches that's will help me a lot.
Thanks in Advance :)

**Comment by QEDady** [comment]
Hi Esraa, 
Sure, we will try to add more of these. Also, please send us some pull requests if you find any good opportunities to share.
